repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    - id: seed-isort-config
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
      exclude: tests/
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.942'
#   hooks:
#    -   id: mypy
#        args: [--ignore-missing-imports, --follow-imports=skip]