language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install coverage mypy flake8 isort  
  - pip install pytest==4.0.0 

script:
  - coverage run -m pytest
  - black --check ./
  - isort ./
  - mypy ./cardioception/ --ignore-missing-imports --follow-imports=skip
  - flake8 ./

after_success:
  - bash <(curl -s https://codecov.io/bash)
